-- SQL SERVER QUERIES FOR DATABASE FIRST

CREATE TABLE [Membro] (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Nome] NVARCHAR(155) NOT NULL,
	[Nascimento] DATETIME NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (SYSDATETIME()),
	[UpdatedAt] DATETIME NOT NULL DEFAULT (SYSDATETIME())
);

GO

CREATE TABLE [Tarefa] (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Titulo] NVARCHAR(155) NOT NULL,
	[Observacao] TEXT,
	[SituacaoId] INT NOT NULL DEFAULT 1,
	[ResponsavelId] INT NOT NULL,
	[AutorId] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (SYSDATETIME()),
	[UpdatedAt] DATETIME NOT NULL DEFAULT (SYSDATETIME())
);

GO

ALTER TABLE [dbo].[Tarefa]  WITH CHECK ADD FOREIGN KEY([ResponsavelId])
REFERENCES [dbo].[Membro] ([Id])

ALTER TABLE [dbo].[Tarefa]  WITH CHECK ADD FOREIGN KEY([AutorId])
REFERENCES [dbo].[Membro] ([Id])
